---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dream.
--- DateTime: 2023/9/15 0:39
---

--- @class LuaProtoc
LuaProtoc = {}

--- @param inputs table
--- @param inputs table
--- @return LuaProtoc
function LuaProtoc.new(inputs, includes)

end

--- @param message_full_name string
--- @param message table
--- @return number[]
function LuaProtoc:encode(message_full_name, message)

end

--- @param message_full_name string
--- @param bytes number[]
--- @return table
function LuaProtoc:decode(message_full_name, bytes)

end

--- @param dirs string[]
--- @return string[]
function LuaProtoc.list_protos(dirs)

end

--- @return FileDescriptor[]
function LuaProtoc:all_file_descriptors()

end

--- @param name string
--- @return FileDescriptor
function LuaProtoc:file_descriptor_by_name(name)

end

--- @return MessageDescriptor[]
function LuaProtoc:all_message_descriptors()

end

--- @param name string
--- @return MessageDescriptor
function LuaProtoc:message_descriptor_by_name(name)

end

--- @return EnumDescriptor[]
function LuaProtoc:all_enum_descriptors()

end

--- @param name string
--- @return EnumDescriptor
function LuaProtoc:enum_descriptor_by_name(name)

end

--- @class FileDescriptor
FileDescriptor = { }

--- @return string
function FileDescriptor:name()

end

--- @return string
function FileDescriptor:package()

end

--- @class MessageDescriptor
MessageDescriptor = {}

--- @class FieldDescriptor
FieldDescriptor = {}

--- @class EnumDescriptor
EnumDescriptor = {}