---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dream.
--- DateTime: 2023/9/15 15:09
---

local pb = require("lua_protobuf_rs")

local protos = pb.list_protos({ "proto" })

local pool = pb.load({ files = protos, includes = { "proto" } })

local player_descriptor = pool:message("com.mikai233.Player")

for _, field in ipairs(player_descriptor.fields) do
    print("field name: " .. field.name .. " number: " .. field.number)
end

print("====")

local login_response_descriptor = pool:message("com.mikai233.LoginResponse")

for _, field in ipairs(login_response_descriptor.fields) do
    if field.type == "message" then
        print(field.type_name)
    end
end
