---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dream.
--- DateTime: 2023/9/15 14:11
---

local pb = require("lua_protobuf_rs")

---@language "protobuf"
local proto = [[
syntax="proto3";

message Player{
  int64 id = 1;
  int64 world_id = 2;
  string nickname = 3;
  int32 exp = 4;
}

message LoginRequest{
  int64 id = 1;
  int64 world_id = 2;
}

message LoginResponse{
  Player player = 1;
}
]]

local pool = pb.load_proto(proto)

local player = {
    id = "2347239423213",
    world_id = "234872389",
    nickname = "mikai233",
    exp = 22000,
}

local player_bytes = pool:encode("Player", player)
local decode_player = pool:decode("Player", player_bytes)
print(decode_player.id)

local login_response_bytes = pool:encode("LoginResponse", { player = player })
local decode_login_response = pool:decode("LoginResponse", login_response_bytes)
print(decode_login_response.player.nickname)
